### ISSUE TITLE
supermicro server not working 

### ISSUE THREAD

**Issue by yaguangtang** [sciapp/nojava-ipmi-kvm#16]
I follow the guide to setup with supermicro servers but docker logs show the below, anything am I missing ? 

2023-02-04 04:53:00,825 DEBG 'javaws' stdout output:
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.

2023-02-04 04:53:01,239 DEBG 'javaws' stdout output:
Attempted to download https://172.16.120.46:443/iKVM__V1.69.40.0x0.jar, but failed to connect!

2023-02-04 04:53:01,255 DEBG 'javaws' stdout output:
Attempted to download https://172.16.120.46:443/liblinux_x86_64__V1.0.15.jar, but failed to connect!

2023-02-04 04:53:01,270 DEBG 'javaws' stdout output:
JAR https://172.16.120.46:443/iKVM__V1.69.40.0x0.jar not found. Continuing.

2023-02-04 04:53:01,282 DEBG 'javaws' stdout output:
JAR https://172.16.120.46:443/liblinux_x86_64__V1.0.15.jar not found. Continuing.

2023-02-04 04:53:01,296 DEBG 'javaws' stdout output:
JAR https://172.16.120.46:443/iKVM__V1.69.40.0x0.jar not found. Continuing.

2023-02-04 04:53:01,311 DEBG 'javaws' stdout output:
JAR https://172.16.120.46:443/liblinux_x86_64__V1.0.15.jar not found. Continuing.

2023-02-04 04:53:01,329 DEBG 'javaws' stdout output:
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.)

2023-02-04 04:53:01,329 DEBG 'javaws' stdout output:
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.

2023-02-04 04:53:01,330 DEBG 'javaws' stdout output:
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:782)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:522)

2023-02-04 04:53:01,330 DEBG 'javaws' stdout output:
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:904)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.

2023-02-04 04:53:01,331 DEBG 'javaws' stdout output:
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:684)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:277)

2023-02-04 04:53:01,331 DEBG 'javaws' stdout output:
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:351)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:418)

2023-02-04 04:53:01,332 DEBG 'javaws' stdout output:
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:394)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:774)

2023-02-04 04:53:01,332 DEBG 'javaws' stdout output:

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by StormYudi** [comment]
I have the same issue on supermicro server, have you resolved this？

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by yaguangtang** [comment]
> I have the same issue on supermicro server, have you resolved this？

please try with the right java version.  java_version: 7u51

**Comment by StormYudi** [comment]
I've tried every version of java, and non of them is working, but after changing to oracle version, it is working now
