### ISSUE TITLE
Docker manifest missing

### ISSUE THREAD

**Issue by jktrigg** [sciapp/nojava-ipmi-kvm#26]
Running on Ubuntu 22.04:
Error response from daemon: No such container: nojava-ipmi-kvmrc-ffd8c89c-e5ab-4a1f-aa8d-91fe73fc256c
Unable to find image 'sciapp/nojava-ipmi-kvm:v0.9.3-openjdk-7' locally
docker: Error response from daemon: manifest for sciapp/nojava-ipmi-kvm:v0.9.3-openjdk-7 not found: manifest unknown: manifest unknown.

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！

**Comment by IngoMeyer441** [comment]
Thanks for the error report. It seems that the latest image did not build successfully. Could you please try to downgrade to `0.9.2` for a quick workaround?

```bash
pip install 'nojava-ipmi-kvm==0.9.2'
```

**Comment by jktrigg** [comment]
That gets me either Docker error 5 (first run after reboot, usually) or the following (any other run, and last time the first run after reboot):
(ikvm) escallop% nojava-ipmi-kvm azurecon             
Password: 
[INFO] Check if 'http://azurecon.scadian.us/' is reachable...
[INFO] The url 'http://azurecon.scadian.us/' is reachable.
[INFO] Starting the Docker container...
Traceback (most recent call last):
  File "/home/blaise/ikvm/lib/python3.10/site-packages/nojava_ipmi_kvm/kvm.py", line 339, in start_kvm_container
    subprocess.check_output(
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blaise/ikvm/bin/nojava-ipmi-kvm", line 8, in <module>
    sys.exit(main())
  File "/home/blaise/ikvm/lib/python3.10/site-packages/nojava_ipmi_kvm/cli.py", line 134, in main
    kvm_viewer = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/blaise/ikvm/lib/python3.10/site-packages/nojava_ipmi_kvm/kvm.py", line 347, in start_kvm_container
    terminate_docker()
  File "/home/blaise/ikvm/lib/python3.10/site-packages/nojava_ipmi_kvm/kvm.py", line 327, in terminate_docker
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'kill', 'nojava-ipmi-kvmrc-7f73b939-afcf-4524-95ae-d23e4e2d1a39']' returned non-zero exit status 1.

**Comment by IngoMeyer441** [comment]
Hmm, currently I don't know what is going on here. Did you try to run with the `--debug` flag?

**Comment by dfuentes87** [comment]
I was getting the same error regarding a missing manifest on 0.9.3:
```
❯ nojava-ipmi-kvm 10.50.50.44 --debug
Password:
[INFO] Check if 'http://10.50.50.44/' is reachable...
[INFO] The url 'http://10.50.50.44/' is reachable.
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
[INFO] Starting the Docker container...
Error response from daemon: No such container: nojava-ipmi-kvmrc-430f8192-413b-4094-a7fb-2ee17d122bd0
Unable to find image 'sciapp/nojava-ipmi-kvm:v0.9.3-openjdk-7' locally
Error response from daemon: No such container: nojava-ipmi-kvmrc-430f8192-413b-4094-a7fb-2ee17d122bd0
Error response from daemon: No such container: nojava-ipmi-kvmrc-430f8192-413b-4094-a7fb-2ee17d122bd0
docker: Error response from daemon: manifest for sciapp/nojava-ipmi-kvm:v0.9.3-openjdk-7 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
[ERROR] Docker terminated with return code 125.
```

I uninstalled 0.9.3, installed 0.9.2, and that version worked fine. This was on macOS 14.5 using pipx

**Comment by Jeff-liaojinfu** [comment]
您的邮件我已经收到，我会尽快回复您！
